export enum ActionType {
  ADD_LIKED_IMG = 'ADD_LIKED_IMG',
  REMOVE_FROM_LIKED_IMG = 'REMOVE_FROM_LIKED_IMG',
  ADD_IMAGE_TO_CART = 'ADD_IMAGE_TO_CART',
  REMOVE_IMAGE_FROM_CART = 'REMOVE_IMAGE_FROM_CART',
}
